name: Proficisci
version: 1.0.0
main: de.mcterranova.proficisci.Proficisci
api-version: 1.21
commands:
  ship:
    description: Manage ships
    usage: /ship <list|tp|name|view>
    permission: proficisci.admin
    permission-message: You do not have permission to use this command.
